site_name: Open Recipes
repo_url: https://github.com/eujoy/openrecipes
docs_dir: ./pages
theme:
  name: null
  custom_dir: themes/cinder
markdown_extensions:
  - admonition
  - toc:
      permalink: '#'
